// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uascslowjmsvcjaksgbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhc2NzbG93am1zdmNqYWtzZ2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDI2ODgsImV4cCI6MjA2NzcxODY4OH0.98Zt-ib0q_PEAPklwKdfeqfu9gQZKXJozZWEkfGQXF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});